% r = parallelGb(TRN,TST,li,imp,...
%   maxNumSplits,minLeafSize,minParentSize,numVariablesToSample,...
%   splitCriterion,predictorSelection,numLearningCycles,learnRate,prior) train a Grading Boost Trees (Grading Boost Trees)
% classifier and return its hyperparameters & performance.
%